config/routes.rb
Rails.application.routes.draw do
  root "contacts#index"

  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  def self.search(search)
    where("lower(name) || phone_number || lower(email) || lower(address) LIKE ?", "%#{search.downcase}%") 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    if params[:search]
      @contacts = Contact.search(params[:search]).order("created_at DESC")
    else
      @contacts = Contact.all.order(:name)
    end
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update(contact_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to root_path
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :email, :phone_number, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/edit.html.erb
<br>
<h1 class='center'>Edit Contact</h1>
<div class='row'>
  <div class='col s4 offset-s4'>
    <%= form_for @contact do |c| %>
      <%= c.label :name %>
      <%= c.text_field :name %>
    
      <%= c.label :phone_number %>
      <%= c.text_field :phone_number %>
    
      <%= c.label :email %>
      <%= c.text_field :email %>
    
      <%= c.label :address %>
      <%= c.text_field :address %>
    
      <%= c.submit class: 'btn grey'%>
    <% end %>
  </div>
</div>

app/views/contacts/index.html.erb
  <h1 class="center grey-text text-darken-3"> Welcome to The Phone Book</h1>
  <hr />
  <center><p class='btn green lighten-2'><%= link_to 'New Contact', new_contact_path, class: 'white-text' %></p></center>
  <br>
  <br>
  <br>
  <div class='row'>
    <div class='col s4 offset-s4'>
      <% if @contacts.present? %>
        <%= render @contacts %>
      <% else %>
        <p>There are no contacts containing the term(s) <%= params[:search] %>.</p>
      <% end %>
      <%= form_tag(contacts_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Contacts" %>
      <%= submit_tag "Search", class: 'btn grey darken-2' %>   <%= link_to 'Show All', root_path, class: 'btn brown lighten-2'%>
      <% end %>
    </div>
  </div>



    <div class='row'>
      <% @contacts.each do |cont| %>
      <div class='col s4'>
        <div class='card panel'>
          <div class="card light-blue darken-3">
            <div class="card-content black-text">
              <span class="card-title"><%= cont.name %></span>
                <p>
                  <%= cont.phone_number %><br>
                  <%= cont.email %><br>
                  <%= cont.address %><br>
                </p> 
            </div>
            <div class="card-action">
              <%= link_to 'Edit', edit_contact_path(cont), class: 'btn grey white-text' %>
              <%= link_to 'Delete', contact_path(cont), method: :delete, class: 'btn red lighten-2 white-text' %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>

app/views/contacts/new.html.erb
<br>
<h1 class='center'>New Contact</h1>
<div class='row'>
  <div class='col s4 offset-s4'>
    <%= form_for @contact do |c| %>
      <%= c.label :name %>
      <%= c.text_field :name %>
    
      <%= c.label :phone_number %>
      <%= c.text_field :phone_number %>
    
      <%= c.label :email %>
      <%= c.text_field :email %>
    
      <%= c.label :address %>
      <%= c.text_field :address %>
    
      <%= c.submit class: "btn green lighten-2" %>
    
    <% end %>
  </div>
</div>

app/views/contacts/show.html.erb
<h1>Contacts#show</h1>
<p>Find me in app/views/contacts/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhoneBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar-fixed">
    <nav id="nav-fix">
      <a href="/" class="brand-logo">Phone Book</a>
      <div class='nav-wrapper'>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
        <%= link_to 'Home', root_path %>
        <%= link_to 'Add Contact', new_contact_path %>
        </ul>
      </div>
    </nav>
  </div>
  <div class='container'>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </div>
</body>
</html>